=== crrromartie/EPAM_Task4_XML-parser/src/main/resources/data/vehicles.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/vehicles"
        xmlns:tns="http://www.example.com/vehicles"
        elementFormDefault="qualified">

    <element name="vehicle" type="tns:Vehicle" abstract="true"/>
    <element name="car" type="tns:Car" substitutionGroup="tns:vehicle"/>
    <element name="truck" type="tns:Truck" substitutionGroup="tns:vehicle"/>
    <element name="bus" type="tns:Bus" substitutionGroup="tns:vehicle"/>

    <element name="vehicles">
        <complexType>
            <sequence>
                <element ref="tns:vehicle"
                         minOccurs="3"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Vehicle">
        <sequence>
            <element name="brand" type="tns:Brand"/>
            <element name="model" type="tns:Model"/>
            <element name="origin" type="tns:Origin"/>
            <element name="price" type="tns:Price"/>
            <element name="chars" type="tns:Chars"/>
            <element name="parameters" type="tns:Parameters"/>
        </sequence>
        <attribute name="id" type="tns:Id" use="required"/>
        <attribute name="description" type="string" use="optional" default="Description..."/>
    </complexType>

    <complexType name="Car">
        <complexContent>
            <extension base="tns:Vehicle">
                <sequence>
                    <element name="awd" type="boolean"/>
                    <element name="acceleration" type="tns:Acceleration"/>
                    <element name="max-speed" type="tns:Max-speed"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Truck">
        <complexContent>
            <extension base="tns:Vehicle">
                <sequence>
                    <element name="cargo-capacity" type="tns:Cargo-capacity"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Bus">
        <complexContent>
            <extension base="tns:Vehicle">
                <sequence>
                    <element name="passenger-capacity" type="tns:Passenger-capacity"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Chars">
        <sequence>
            <element name="fuel-type" type="tns:Fuel-type"/>
            <element name="power" type="tns:Power"/>
            <element name="fuel-consumption" type="tns:Fuel-consumption"/>
            <element name="transmission" type="tns:Transmission"/>
        </sequence>
    </complexType>

    <complexType name="Parameters">
        <sequence>
            <element name="length" type="tns:Length"/>
            <element name="width" type="tns:Width"/>
            <element name="weight" type="tns:Weight"/>
        </sequence>
    </complexType>

    <simpleType name="Length">
        <restriction base="double">
            <minInclusive value="1.0"/>
            <maxInclusive value="10.0"/>
        </restriction>
    </simpleType>

    <simpleType name="Width">
        <restriction base="double">
            <minInclusive value="0.5"/>
            <maxInclusive value="3.5"/>
        </restriction>
    </simpleType>

    <simpleType name="Weight">
        <restriction base="positiveInteger">
            <minInclusive value="500"/>
            <maxInclusive value="10000"/>
        </restriction>
    </simpleType>

    <simpleType name="Brand">
        <restriction base="string">
            <pattern value="[\w|\s]{1,20}"/>
        </restriction>
    </simpleType>

    <simpleType name="Model">
        <restriction base="string">
            <pattern value="[\w|\s]{1,20}"/>
        </restriction>
    </simpleType>

    <simpleType name="Origin">
        <restriction base="string">
            <pattern value="[\w|\s]{1,20}"/>
        </restriction>
    </simpleType>

    <simpleType name="Price">
        <restriction base="positiveInteger">
            <minInclusive value="1000"/>
            <maxInclusive value="100000"/>
        </restriction>
    </simpleType>

    <simpleType name="Power">
        <restriction base="positiveInteger">
            <minInclusive value="20"/>
            <maxInclusive value="2000"/>
        </restriction>
    </simpleType>

    <simpleType name="Fuel-type">
        <restriction base="string">
            <enumeration value="diesel"/>
            <enumeration value="gasoline"/>
        </restriction>
    </simpleType>

    <simpleType name="Fuel-consumption">
        <restriction base="double">
            <minInclusive value="1.0"/>
            <maxInclusive value="100.0"/>
        </restriction>
    </simpleType>

    <simpleType name="Transmission">
        <restriction base="string">
            <enumeration value="automatic"/>
            <enumeration value="manual"/>
        </restriction>
    </simpleType>

    <simpleType name="Acceleration">
        <restriction base="double">
            <minInclusive value="1.0"/>
            <maxInclusive value="60.0"/>
        </restriction>
    </simpleType>

    <simpleType name="Max-speed">
        <restriction base="positiveInteger">
            <minInclusive value="30"/>
            <maxInclusive value="450"/>
        </restriction>
    </simpleType>

    <simpleType name="Cargo-capacity">
        <restriction base="positiveInteger">
            <minInclusive value="100"/>
            <maxInclusive value="20000"/>
        </restriction>
    </simpleType>

    <simpleType name="Passenger-capacity">
        <restriction base="positiveInteger">
            <minInclusive value="3"/>
            <maxInclusive value="100"/>
        </restriction>
    </simpleType>

    <simpleType name="Id">
        <restriction base="ID">
            <pattern value="Id-\d+"/>
        </restriction>
    </simpleType>

</schema>

=== crrromartie/EPAM_Task4_XML-parser/src/main/resources/data/dataForTest.xml
<?xml version="1.0" encoding="UTF-8" ?>
<vehicles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/vehicles"
          xsi:schemaLocation="http://www.example.com/vehicles vehicles.xsd">

    <car id="Id-1">
        <brand>Audi</brand>
        <model>A4</model>
        <origin>Germany</origin>
        <price>36000</price>
        <chars>
            <fuel-type>diesel</fuel-type>
            <power>194</power>
            <fuel-consumption>5.8</fuel-consumption>
            <transmission>automatic</transmission>
        </chars>
        <parameters>
            <length>4.56</length>
            <width>1.86</width>
            <weight>2000</weight>
        </parameters>
        <awd>true</awd>
        <acceleration>8.2</acceleration>
        <max-speed>225</max-speed>
    </car>

    <truck id="Id-2">
        <brand>Fiat</brand>
        <model>Ducato</model>
        <origin>Italy</origin>
        <price>27000</price>
        <chars>
            <fuel-type>diesel</fuel-type>
            <power>180</power>
            <fuel-consumption>8.3</fuel-consumption>
            <transmission>manual</transmission>
        </chars>
        <parameters>
            <length>5.83</length>
            <width>1.88</width>
            <weight>4000</weight>
        </parameters>
        <cargo-capacity>1500</cargo-capacity>
    </truck>

    <bus id="Id-3">
        <brand>Ford</brand>
        <model>Transit</model>
        <origin>USA</origin>
        <price>27000</price>
        <chars>
            <fuel-type>diesel</fuel-type>
            <power>125</power>
            <fuel-consumption>8.8</fuel-consumption>
            <transmission>manual</transmission>
        </chars>
        <parameters>
            <length>6.5</length>
            <width>1.9</width>
            <weight>4600</weight>
        </parameters>
        <passenger-capacity>17</passenger-capacity>
    </bus>

</vehicles>

=== crrromartie/EPAM_Task4_XML-parser/src/main/resources/data/vehicles.xml
<?xml version="1.0" encoding="UTF-8" ?>
<vehicles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/vehicles"
          xsi:schemaLocation="http://www.example.com/vehicles vehicles.xsd">

    <car id="Id-1" description="Cool car!">
        <brand>Audi</brand>
        <model>A4</model>
        <origin>Germany</origin>
        <price>36000</price>
        <chars>
            <fuel-type>diesel</fuel-type>
            <power>194</power>
            <fuel-consumption>5.8</fuel-consumption>
            <transmission>automatic</transmission>
        </chars>
        <parameters>
            <length>4.56</length>
            <width>1.86</width>
            <weight>2000</weight>
        </parameters>
        <awd>true</awd>
        <acceleration>8.2</acceleration>
        <max-speed>225</max-speed>
    </car>

    <truck id="Id-2">
        <brand>Fiat</brand>
        <model>Ducato</model>
        <origin>Italy</origin>
        <price>27000</price>
        <chars>
            <fuel-type>diesel</fuel-type>
            <power>180</power>
            <fuel-consumption>8.3</fuel-consumption>
            <transmission>manual</transmission>
        </chars>
        <parameters>
            <length>5.83</length>
            <width>1.88</width>
            <weight>4000</weight>
        </parameters>
        <cargo-capacity>1500</cargo-capacity>
    </truck>

    <bus id="Id-3">
        <brand>Ford</brand>
        <model>Transit</model>
        <origin>USA</origin>
        <price>27000</price>
        <chars>
            <fuel-type>diesel</fuel-type>
            <power>125</power>
            <fuel-consumption>8.8</fuel-consumption>
            <transmission>manual</transmission>
        </chars>
        <parameters>
            <length>6.5</length>
            <width>1.9</width>
            <weight>4600</weight>
        </parameters>
        <passenger-capacity>17</passenger-capacity>
    </bus>

    <car id="Id-4">
        <brand>Honda</brand>
        <model>Civic</model>
        <origin>Japan</origin>
        <price>28000</price>
        <chars>
            <fuel-type>gasoline</fuel-type>
            <power>172</power>
            <fuel-consumption>6.5</fuel-consumption>
            <transmission>automatic</transmission>
        </chars>
        <parameters>
            <length>4.57</length>
            <width>1.75</width>
            <weight>1680</weight>
        </parameters>
        <awd>false</awd>
        <acceleration>8.4</acceleration>
        <max-speed>220</max-speed>
    </car>

    <truck id="Id-5">
        <brand>Iveco</brand>
        <model>Daily</model>
        <origin>Italy</origin>
        <price>28500</price>
        <chars>
            <fuel-type>diesel</fuel-type>
            <power>163</power>
            <fuel-consumption>9.2</fuel-consumption>
            <transmission>automatic</transmission>
        </chars>
        <parameters>
            <length>5.73</length>
            <width>1.79</width>
            <weight>4300</weight>
        </parameters>
        <cargo-capacity>1650</cargo-capacity>
    </truck>

    <bus id="Id-6">
        <brand>Mercedes</brand>
        <model>Sprinter</model>
        <origin>Germany</origin>
        <price>27000</price>
        <chars>
            <fuel-type>diesel</fuel-type>
            <power>169</power>
            <fuel-consumption>9.2</fuel-consumption>
            <transmission>automatic</transmission>
        </chars>
        <parameters>
            <length>6.4</length>
            <width>1.85</width>
            <weight>4650</weight>
        </parameters>
        <passenger-capacity>19</passenger-capacity>
    </bus>

    <car id="Id-7">
        <brand>Ford</brand>
        <model>Mondeo</model>
        <origin>USA</origin>
        <price>31000</price>
        <chars>
            <fuel-type>gasoline</fuel-type>
            <power>175</power>
            <fuel-consumption>6.9</fuel-consumption>
            <transmission>automatic</transmission>
        </chars>
        <parameters>
            <length>4.87</length>
            <width>1.85</width>
            <weight>2100</weight>
        </parameters>
        <awd>false</awd>
        <acceleration>9.7</acceleration>
        <max-speed>210</max-speed>
    </car>

    <truck id="Id-8">
        <brand>Renault</brand>
        <model>Mascott</model>
        <origin>France</origin>
        <price>28500</price>
        <chars>
            <fuel-type>diesel</fuel-type>
            <power>138</power>
            <fuel-consumption>9.4</fuel-consumption>
            <transmission>manual</transmission>
        </chars>
        <parameters>
            <length>6.1</length>
            <width>2.1</width>
            <weight>5500</weight>
        </parameters>
        <cargo-capacity>3000</cargo-capacity>
    </truck>

    <bus id="Id-9">
        <brand>Volkswagen</brand>
        <model>Crafter</model>
        <origin>Germany</origin>
        <price>32000</price>
        <chars>
            <fuel-type>diesel</fuel-type>
            <power>180</power>
            <fuel-consumption>8.7</fuel-consumption>
            <transmission>manual</transmission>
        </chars>
        <parameters>
            <length>6.3</length>
            <width>1.87</width>
            <weight>4620</weight>
        </parameters>
        <passenger-capacity>18</passenger-capacity>
    </bus>
</vehicles>
